// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2wwjr6XShFo3AvcHDOCsVXeTvqUti5Zk',
    appId: '1:132576266640:web:eec46b6e80b42723bb0b15',
    messagingSenderId: '132576266640',
    projectId: 'maghali',
    authDomain: 'maghali.firebaseapp.com',
    storageBucket: 'maghali.firebasestorage.app',
    measurementId: 'G-5ZEDHLXS2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhWXpoWXTsstZ0l8y8_7CMPRFH59qZxZA',
    appId: '1:132576266640:android:6478c6b4bb44fc39bb0b15',
    messagingSenderId: '132576266640',
    projectId: 'maghali',
    storageBucket: 'maghali.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk-V19W6n6dgryt9FH5kkGmnCW2dtwhMY',
    appId: '1:132576266640:ios:9b02956d7f664180bb0b15',
    messagingSenderId: '132576266640',
    projectId: 'maghali',
    storageBucket: 'maghali.firebasestorage.app',
    iosBundleId: 'com.example.maghali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk-V19W6n6dgryt9FH5kkGmnCW2dtwhMY',
    appId: '1:132576266640:ios:9b02956d7f664180bb0b15',
    messagingSenderId: '132576266640',
    projectId: 'maghali',
    storageBucket: 'maghali.firebasestorage.app',
    iosBundleId: 'com.example.maghali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2wwjr6XShFo3AvcHDOCsVXeTvqUti5Zk',
    appId: '1:132576266640:web:ff9bc5f9efc9c160bb0b15',
    messagingSenderId: '132576266640',
    projectId: 'maghali',
    authDomain: 'maghali.firebaseapp.com',
    storageBucket: 'maghali.firebasestorage.app',
    measurementId: 'G-74ZXPKF23T',
  );
}
